"use client";

import './globals.scss'
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";

// Import Montserrat
export const MONTSERRAT = Montserrat({
  variable: '--default-font',
  subsets: ["latin"],
  display: "swap"
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  const preventRightClick = (e: any) => {
    e.preventDefault()
  }

  return (
    <html lang="en">
      <style jsx global>{`
        :root {
          --default-font: ${MONTSERRAT.style.fontFamily}
        }
      `}</style>
      <body onContextMenu={preventRightClick}>{children}</body>
    </html>
  )
}
